### ISSUE TITLE
00004000 - Asura's Wrath (+DLC)

### ISSUE THREAD

**Issue by Arjuna2227** [xenia-canary/game-compatibility#206]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a canary branch. (not MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xbox 360 Marketplace link

https://marketplace.xbox.com/de-DE/Product/ASURAS-WRATH/66acd000-77fe-1000-9115-d80243430817

### Xenia version

https://github.com/xenia-canary/xenia-canary/commit/529d45398634287b12c7f5552b0188bbe539398f

### Issues

Game plays from start to finish. No issues found. 

The DLC episode can also be easily installed. 

### Log

[xenia - Copy.zip](https://github.com/xenia-canary/game-compatibility/files/14469933/xenia.-.Copy.zip)

### Screenshots

<img width="960" alt="Screenshot 2024-03-02 165636" src="https://github.com/xenia-canary/game-compatibility/assets/103894458/b8e4756b-c0f6-4e88-bb66-e10fcfda26b7">

### Labels

state-playable

**Comment by Margen67** [comment]
Title ID is invalid and missing from log.
