### ISSUE TITLE
4D5308B3 - Kinectimals

### ISSUE THREAD

**Issue by wheelmac92** [xenia-canary/game-compatibility#21]
Xenia Canary Jan 14 2020

xenia-canary.zip

xeniaLog_30mb.zip

The following screenshots are from d3d12. The results were almost the same in Vulkan

image

image

image

**Comment by illusion98** [comment]
Not following template. Missing images, logs, commit links.

**Comment by wheelmac92** [comment]
@illusion98 I just put them in

**Comment by illusion98** [comment]
Still not following the temple

**Comment by illusion98** [comment]
Look at other issues for examples. Once edited it will be re opened
