### ISSUE TITLE
4E4D07F5 - Dead to Rights: Retribution

### ISSUE THREAD

**Issue by kortul** [xenia-canary/game-compatibility#231]
### Validation

- [X] I've read the [FAQ](https://github.com/xenia-canary/xenia-canary/wiki/FAQ).
- [X] The Xenia build used is from a canary branch. (not MLBS/AlexVS/master/pull requests, etc)
- [X] This issue isn't for help (tech support) with Xenia, or a game.
- [X] I've checked if this game doesn't already have a compatibility report.

### Xenia version

https://github.com/xenia-canary/xenia-canary/commit/.../

### Issues

- Fully playable!
- Runs great with unlocked frame rate
- GAC Pack DLC also fully playable, requires Title Update: TU_174Q1VL_0000004000000

**Issues:**

- Flickering:
*Setting the config to internal_display_resolution = 16  fixed the flickering for me

- Some mission objectives fail with unlocked frame rate - have to turn on VSYNC in Xenia config for the following sections to progress:

*Chapter 4: End of The Line. At the Grand Central building where you have to disarm 3 bombs, the objective will fail when disarming the last bomb without VSYNC

- Assault rifle gun sound might occasionaly cut out, fixes itself on the next reload.

### Log

[xenia.log.zip](https://github.com/user-attachments/files/16324048/xenia.log.zip)

### Screenshots
![dead_to_rights_retribution_banner](https://github.com/user-attachments/assets/5378655b-35c4-44c7-b6d8-6c80ba776425)
![5](https://github.com/user-attachments/assets/1baeb426-f384-4b5c-a985-69aef572548c)
![1](https://github.com/user-attachments/assets/57c408d1-a0cc-41c5-81ee-7790295bce7c)
![2](https://github.com/user-attachments/assets/e29101c0-7f6b-490d-af5a-92fb702736a9)
![3](https://github.com/user-attachments/assets/8ad07521-7a3a-4545-aced-77dc065e7ae9)
![4](https://github.com/user-attachments/assets/bf2c8469-edce-4437-8316-cebef4129960)

### Labels
state-playable

**Comment by Margen67** [comment]
Log is from master and commit hash is missing.
