### ISSUE TITLE
555307EE - Import Tuner Challenge

### ISSUE THREAD

**Issue by Saturn185** [xenia-canary/game-compatibility#79]
Issues:
Crashes if tries to load the story menu at normal speed

Log:
[ITC.zip](https://github.com/xenia-canary/game-compatibility/files/6135219/ITC.zip)

Screenshot(s):
![160014950_449120272967718_943836687431120729_n](https://user-images.githubusercontent.com/79617156/111012956-ac5bdf80-8395-11eb-8d71-1733bb660901.jpg)

Labels:
state-gameplay

**Comment by Saturn185** [comment]
i've completed the game 100% using the latest xenia canary build as of this comment 
and as well as putting the emulator at 2x speed before going into the story mode menu  
that also applies loading saves and when about to beat a boss, also in rare occasions (3 times i believe) 
random cars would turn invisible while still having collision and when that happened the game always crashed 
going back to the menu regardless of speed

**Comment by illusion0001** [comment]
Still no proper xenia log file and commit link
